name: Deploy on main branch push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy with Git rollback
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            set -e

            APP_DIR="${{ secrets.APP_DIR }}"
            cd "$APP_DIR"

            PREV_COMMIT=$(git rev-parse HEAD)
            git fetch origin main
            git reset --hard origin/main
            docker compose down

            if docker compose up --build -d; then
              echo "[SUCCESS] Deployment completed."
              exit 0
            else
              echo "[ERROR] Deployment failed. Rolling back..."
              git reset --hard "$PREV_COMMIT"
              docker compose down
              docker compose up -d
              echo "[ROLLBACK] Previous version restored."
              exit 0
            fi
          '
